
platform :ios, '9.0'
use_frameworks!

target 'NetworkDemo' do

	pod 'Alamofire'
    pod 'RxSwift'
    pod 'RxCocoa'
    #pod 'SwiftyJSON'
    pod 'Moya'
	pod 'Moya/RxSwift'
    pod 'ObjectMapper'
    
end
